### ISSUE TITLE
Outdated mongodb driver

### ISSUE THREAD

**Issue by Booster2ooo** [louischatriot/nedb-to-mongodb#6]
Hi,

When I tried to use transfert.js, I came accros this error:
MongoError: driver is incompatible with this server version

I fixed it by simply installing lastest version of the mongodb driver for node
npm install mongodb@latest

Regards

**Comment by citymont** [comment]
just add MongoDB to "latest" in your package.json like this : 

``
"mongodb": "latest"
``

**Comment by louischatriot** [comment]
Well it depends on the version of mongodb you're using. I agree the default should be "latest" so I'll modify the package.json but I'm not in favor in forcing the use of latest version in this setup.

**Comment by crapthings** [comment]
this is a fork work with latest mongodb driver
https://github.com/crapthings/nedb-to-mongodb
