### ISSUE TITLE
Could not get it to work

### ISSUE THREAD

**Issue by zevero** [louischatriot/nedb-to-mongodb#7]
I am outgrown out of nedb ... I love the simplicity and use it for quite a while for some little projects in production. But now I need to open a db twice, so I need to upgrade to mongodb.

Unfortunately, on npm install I got the following:

    severin@schenker:~/node/nedb-to-mongodb$ npm install

    > kerberos@0.0.14 install /home/severin/node/nedb-to-mongodb/node_modules/kerberos
    > (node-gyp rebuild) || (exit 0)

    make: Entering directory '/home/severin/node/nedb-to-mongodb/node_modules/kerberos/build'
      CXX(target) Release/obj.target/kerberos/lib/kerberos.o
    In file included from ../lib/kerberos.cc:1:0:
    ../lib/kerberos.h:5:27: fatal error: gssapi/gssapi.h: Datei oder Verzeichnis nicht gefunden
     #include <gssapi/gssapi.h>
                               ^
    compilation terminated.
    kerberos.target.mk:94: recipe for target 'Release/obj.target/kerberos/lib/kerberos.o' failed
    make: *** [Release/obj.target/kerberos/lib/kerberos.o] Error 1
    make: Leaving directory '/home/severin/node/nedb-to-mongodb/node_modules/kerberos/build'
    gyp ERR! build error 
    gyp ERR! stack Error: `make` failed with exit code: 2
    gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
    gyp ERR! stack     at emitTwo (events.js:87:13)
    gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
    gyp ERR! System Linux 3.16.0-4-amd64
    gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
    gyp ERR! cwd /home/severin/node/nedb-to-mongodb/node_modules/kerberos
    gyp ERR! node -v v4.1.1
    gyp ERR! node-gyp -v v3.0.3
    gyp ERR! not ok 

    > kerberos@0.0.14 install /home/severin/node/nedb-to-mongodb/node_modules/kerberos
    > (node-gyp rebuild) || (exit 0)

    make: Entering directory '/home/severin/node/nedb-to-mongodb/node_modules/kerberos/build'
      CXX(target) Release/obj.target/kerberos/lib/kerberos.o
    In file included from ../lib/kerberos.cc:1:0:
    ../lib/kerberos.h:5:27: fatal error: gssapi/gssapi.h: Datei oder Verzeichnis nicht gefunden
     #include <gssapi/gssapi.h>
                               ^
    compilation terminated.
    kerberos.target.mk:94: recipe for target 'Release/obj.target/kerberos/lib/kerberos.o' failed
    make: *** [Release/obj.target/kerberos/lib/kerberos.o] Error 1
    make: Leaving directory '/home/severin/node/nedb-to-mongodb/node_modules/kerberos/build'
    gyp ERR! build error 
    gyp ERR! stack Error: `make` failed with exit code: 2
    gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
    gyp ERR! stack     at emitTwo (events.js:87:13)
    gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
    gyp ERR! System Linux 3.16.0-4-amd64
    gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
    gyp ERR! cwd /home/severin/node/nedb-to-mongodb/node_modules/kerberos
    gyp ERR! node -v v4.1.1
    gyp ERR! node-gyp -v v3.0.3
    gyp ERR! not ok 
    nedb-to-mongodb@0.1.0 /home/severin/node/nedb-to-mongodb
    +-- async@0.2.10 
    +-- commander@1.1.1 
    | `-- keypress@0.1.0 
    +-- mongodb@2.0.45 
    | +-- es6-promise@2.1.1 
    | +-- mongodb-core@1.2.14 
    | | +-- bson@0.4.12 
    | | `-- kerberos@0.0.14 
    | |   `-- nan@2.0.9 
    | `-- readable-stream@1.0.31 
    |   +-- core-util-is@1.0.1 
    |   +-- inherits@2.0.1 
    |   +-- isarray@0.0.1 
    |   `-- string_decoder@0.10.31 
    `-- nedb@1.2.1 
      +-- binary-search-tree@0.2.4 
      +-- mkdirp@0.5.1 
      | `-- minimist@0.0.8 
      `-- underscore@1.4.4 

    npm WARN EPACKAGEJSON nedb-to-mongodb@0.1.0 No license field.

when I try to convert a db I get:

    severin@schenker:~/node/nedb-to-mongodb$ ./transfer.js -n ../mlt/data/device.db -d mlt -c device -k true
    NEED SOME HELP? Type ./transfer.js --help
    -----------------------------------------
    No MongoDB host provided, using default (localhost)
    No MongoDB port provided, using default (27017)
    Connected to mongodb://localhost:27017/mlt
    /home/severin/node/nedb-to-mongodb/transfer.js:72
        if (ndb.data.length === 0) {
                    ^

    TypeError: Cannot read property 'length' of undefined
        at /home/severin/node/nedb-to-mongodb/transfer.js:72:17
        at callback (/home/severin/node/nedb-to-mongodb/node_modules/nedb/lib/executor.js:30:17)
        at /home/severin/node/nedb-to-mongodb/node_modules/nedb/lib/persistence.js:361:15
        at /home/severin/node/nedb-to-mongodb/node_modules/nedb/lib/persistence.js:170:72
        at /home/severin/node/nedb-to-mongodb/node_modules/nedb/lib/persistence.js:90:50
        at FSReqWrap.oncomplete (fs.js:82:15)
    severin@schenker:~/node/nedb-to-mongodb$ ./transfer.js -n ../mlt/data/device.db -d mlt -c device -k true

my device.db looks like

    {"user_id":"Will","t_create":1437374673913,"t_last":1438006838253,"_id":"UVA5tucyVf0AAtcP"}
    {"user_id":"Gast","t_create":1437741400389,"t_last":1437742019066,"_id":"UbmIbJzWRTmqd92O"}
    {"user_id":"Hoffmann","t_create":1436352171086,"t_last":1437817647101,"_id":"VEctPHZz3tvcAqyb"}

what about my IDs. Can I keep using my _ids in mongodb?

Thank you!

**Comment by zevero** [comment]
Oh I solved the first part of my question npm install requires

    sudo apt-get install libkrb5-dev

Unfortunately, I still get the same error
  
    if (ndb.data.length === 0) {
                    ^
    TypeError: Cannot read property 'length' of undefined

Thanks!

**Comment by louischatriot** [comment]
Please follow the bug reporting guidelines when reporting a bug, before I can consider it: https://github.com/louischatriot/nedb#bug-reporting-guidelines

I'll reopen upon resubmit

**Comment by aruethe2** [comment]
I ran into the same issue.  I changed all occurrences of ndb.data to  ndb.getAllData() in transfer.js and that seemed to fix the problem.

**Comment by tsipizic** [comment]
I confirm that above suggestion fixes the issue.

**Comment by zevero** [comment]
Yes solution of @aruethe2 works nicely.
I hope @louischatriot can reconsider this bug on the basis of your confirmation.

**Comment by zevero** [comment]
Just transfered some tables an ran again into this issue :)
Current Version is still broken.
Please @louischatriot  reopen and simply change all occurrences of ndb.data to ndb.getAllData() in transfer.js as @aruethe2 suggested.
Everything works very fine otherwise.
Thank you very much!

**Comment by zevero** [comment]
Just needed it again - it did not work - luckily I found my own pull request witch solved my problem :8ball: 

Please simply change all occurrences of ndb.data to ndb.getAllData() in transfer.js
and state that npm install needs
sudo apt-get install libkrb5-dev
installed!

It really works fine!
Thank you so much!

**Comment by crapthings** [comment]
this is a fork work with latest mongodb driver
https://github.com/crapthings/nedb-to-mongodb
